version: '3'
services:
  users:
    build:
      context: ./packages/users
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - ./packages/users/src:/src
  notifications:
    build:
      context: ./packages/notifications
      dockerfile: dev.Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./packages/notifications/src:/src
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    ports: 
      - 5672:5672
      - 15672:15672
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - dataDb:/data/db
    ports:
      - 27017:27017
volumes:
  dataDb: