version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:chakracore

    working_directory: ~/repo

    steps:
      - run: git --version
      - run: mkdir ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: git clone https://github.com/microservices-imie/services .
      - run: git clone https://github.com/ingydotnet/git-subrepo ../git-subrepo
      - run: cd ../git-subrepo && source .rc && echo $GIT_SUBREPO_ROOT && cd ../repo && echo yes | git subrepo push --all --verbose --branch=master