version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:chakracore

    working_directory: ~/repo

    steps:
      - run: git clone git@github.com:microservices-imie/services.git .
      - run: git clone https://github.com/ingydotnet/git-subrepo ../git-subrepo
      - run: cd ../git-subrepo && source .rc && echo $GIT_SUBREPO_ROOT && cd ../repo && git subrepo push --all 